# Config
# ========================================================================================

# IMPORTANT: Set the URL of your site.
url:                   https://yanniscs.github.io

# IMPORTANT: Set The "base URL" of your site.
baseurl:               ''

# Language of your content in 2-letter code
lang:                  en

# The title of your blog. Used in the sidebar and the browser tab.
title:                 Yanna Shen

# A short description (~150 chars) of the page used for the meta description tag.
description:           >
  A showcase of my projects.

# A shorter description for the sidebar. previous: Developer Portfolio
tagline:               >
  click to view or download

# A list of keywords for your blog
keywords:              []

# Used by jekyll-seo-tag...
logo:                  /assets/icons/icon.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  name:                Yanna Shen
  email:               yanna.cshen@gmail.com
  # twitter:             <username>
  picture:             /assets/img/i_and_ww_discovery_square.jpg
# Menu links - EDITED: Removed Hyde, Hydejack, Documentation
# Menu links - UPDATED: Switched order of About Me and Projects
menu:
  - title:             About Me
    url:               /about/
  - title:             Projects
    url:               /projects

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2025. All rights reserved.

# Format of the permalinks
permalink:             pretty

# Pagination configuration (used by the `blog` layout)
paginate:              5
paginate_path:         /page-:num/

# Customizaton
# ========================================================================================

# Sidebar image and theme color of the site.
accent_image:          /assets/img/sidebar-bg.jpg
accent_color:          '#4fb1ba'

# The string encoding which fonts to fetch from Google Fonts.
google_fonts:          Roboto+Slab:700|Noto+Sans:400,400i,700,700i

# The text font. Expects a string that is a valid CSS font-family value.
font:                  Noto Sans, Helvetica, Arial, sans-serif

# The font used for headings. Expects a string that is a valid CSS font-family value.
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif

# Hydejack Settings
# ----------------------------------------------------------------------------------------
hydejack:
  # Configure the order of complementary content on project pages
  project_addons:      [about, other]

  # If you do not use Google Fonts, set to `true`.
  no_google_fonts:     false

  # Set to `true` if you don't want to show an icon indicating external links
  no_mark_external:    false

  # Set to `true` if third party plugins fail to work with dynamically loaded pages
  no_push_state:       false

  # Set to `true` if you want to disable the drawer
  no_drawer:           false

  # Set to `true` if you do not want parts of the css inlined in <head/>
  no_inline_css:       false

  # Code blocks and tables "break" the layout by spanning the full available width.
  no_break_layout:     false

  # Set to `true` if you do not want to expose your resume and projects
  # in machine-readable formats.
  no_structured_data:  false

  # Set to `true` when building with the `--lsi` option
  use_lsi:             false

  # When using Google Analytics, set to `true` to display a cookie notice banner.
  cookies_banner:      false

# Collections
# ========================================================================================

collections:
  projects:
    permalink:         /projects/:path/
    output:            true
  featured_categories:
    permalink:         /category/:name/
    output:            true
  featured_tags:
    permalink:         /tag/:name/
    output:            true

# File inclusion/exclusion
# ========================================================================================

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
include:
  - LICENSE.md

# Plugins and Plugin Configuration
# ========================================================================================

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme
# ---------------------------------------------------------------------------------------

# Use the remote theme setting for GitHub Pages
remote_theme: hydecorp/hydejack@v7

# Markdown Processing
# ---------------------------------------------------------------------------------------

kramdown:
  footnote_backlink:   '&#x21a9;&#xfe0e;'
  math_engine:         mathjax
  math_engine_opts:
    preview:           true
    preview_as_code:   true

# HTML Compression
# ---------------------------------------------------------------------------------------

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed